package com.charles.warmwords.app.ui.theme

import androidx.compose.ui.graphics.Color

val WarmCream = Color(0xFFFCF5ED)
val WarmCreamDark = Color(0xFFF5ECE1)
val WarmOrange = Color(0xFFFF8C42)
val WarmOrangeLight = Color(0xFFFFA673)
val WarmOrangeDark = Color(0xFFE07535)
val WarmTeal = Color(0xFF4DB6AC)
val WarmTealLight = Color(0xFF80CBC4)
val WarmTealDark = Color(0xFF00897B)
val WarmPink = Color(0xFFF8BBD9)
val WarmPurple = Color(0xFFCE93D8)
val WarmLavender = Color(0xFFE1BEE7)
val SoftYellow = Color(0xFFFFECB3)
val SoftPeach = Color(0xFFFFCCBC)
val GentleGray = Color(0xFFE0E0E0)
val GentleGrayDark = Color(0xFFBDBDBD)
val TextPrimary = Color(0xFF212121)
val TextSecondary = Color(0xFF757575)
val TextOnPrimary = Color(0xFFFFFFFF)
val ErrorRed = Color(0xFFEF5350)
val WarningAmber = Color(0xFFFFC107)
val SuccessGreen = Color(0xFF66BB6A)
val CardBackground = Color(0xFFFFFFFF)
val CardBackgroundDark = Color(0xFF2D2A27)
val SurfaceVariant = Color(0xFFF5F5F5)
val SurfaceVariantDark = Color(0xFF423E3A)
val WarmDarkBackground = Color(0xFF1E1B18)
val TextPrimaryDark = Color(0xFFF2ECE6)
val TextSecondaryDark = Color(0xFFC4BCB4)
